### ISSUE TITLE
Extrair dados das turmas do SIGAA

### ISSUE THREAD

**Issue by Genaina** [EngSwCIC/CAMAAR#1]
Eu como Administrador 
Quero extrair do SIGAA dados relativos às turmas do CIC no semestre corrente 
A fim de alimentar a base de dados do sistema

**Comment by EduardoLR10** [comment]
Eu como Administrador
Quero extrair do SIGAA dados relativos às turmas do CIC no semestre corrente
A fim de visualizar quais dados serão importados na base de dados do sistema
