### ISSUE TITLE
Criar menu principal

### ISSUE THREAD

**Issue by CPeluti** [EngSwCIC/CAMAAR#39]
Eu como usuário
Quero ver as opções que posso utilizar no sistema
A fim de escolher qual ferramenta irei utilizar

**Comment by CPeluti** [comment]
Lembrando que as opções que devem ser mostradas tem que levar em consideração quais permissões o usuário tem ( permissão de coordenador, professor ou aluno)

**Comment by Pericles12** [comment]
Caio, boa tarde !!!!

No caso no aluno  tenho as seguintes dúvidas?  
O aluno recebe a notificação e preenche as informações no sistema e isso?
Então, a alimentação do sistema seria feita diretamente por cada aluno cadastrado ?
Como autenticar o cadastro do aluno com o siga ?
Quais seriam os itens para atender o cadastro do aluno ? email institucional e suficiente ?

**Comment by Pericles12** [comment]
Qual a diferença entre esses relatórios :  3) Gerar relatório do administrador, 4)Gerar relatório sobre as avaliações dos alunos, 5) Gerar relatório de avaliação aos professores  ?
A Rotina Gerar relatório do administrador engloba , engloba os itens 4 e 5 ? 
Não haverá relatório por disciplina ?

**Comment by Pericles12** [comment]
Caio, pelo que vi no Backend o cadastro do usuário esta condicionado a existência do email institucional 
" senha = User.new(:password => params[:senha_pessoa]).encrypted_password
      if Member.exists?(:email=> email) && !User.exists?(:email=> email)
            member = Member.find_by(:email => email)" 
Desta vi requisitos para o formato da senha cadastrada  ou estou errado ?
Posso condicionar o cadastro ao email institucional e também a token recebido ?

**Comment by CPeluti** [comment]
> Qual a diferença entre esses relatórios : 3) Gerar relatório do administrador, 4)Gerar relatório sobre as avaliações dos alunos, 5) Gerar relatório de avaliação aos professores ? A Rotina Gerar relatório do administrador engloba , engloba os itens 4 e 5 ? Não haverá relatório por disciplina ?

No caso a principio os relatórios são separados somente por questionário, desse modo temos que o relatório do aluno e do professor serão basicamente os mesmos, diferindo apenas de qual questionários são referenciados.
Já no caso do relatório do administrador, é interessante que tenha um overview geral, para que consiga ter acesso a informações de múltiplos questionários de uma maneira mais condensada.
