### ISSUE TITLE
Importar dados do SIGAA

### ISSUE THREAD

**Issue by Genaina** [EngSwCIC/CAMAAR#4]
Eu como Administrador 
Quero importar no CAMAAR dados relativos às turmas do CIC no semestre corrente 
A fim de alimentar a base de dados do sistema

**Comment by EduardoLR10** [comment]
Eu como Administrador
Quero visualizar no CAMAAR os dados extraídos do SIGAA relativos às turmas do CIC no semestre corrente
A fim de alimentar a base de dados do sistema
