### ISSUE TITLE
Aprimorar os relatórios

### ISSUE THREAD

**Issue by CPeluti** [EngSwCIC/CAMAAR#42]
Eu como administrador
Quero visualizar as avaliações de todas a turmas de uma maneira rápida e simples
A fim de avaliar o desempenho das turmas do CIC no semestre atual

**Comment by CPeluti** [comment]
Utilizar alternativas como gráficos e drilldowns para exibir as informações de maneira mais interessante.

**Comment by m4ycon** [comment]
Acho ruim limitar essa consulta ao semestre atual, talvez ter um query param para o semestre seria melhor? Ou realmente não importa as pesquisas dos semestres passados? 

E como saberiamos o semestre atual? Por data não da, um exemplo é esse ano que vão ter 3 semestres

**Comment by m4ycon** [comment]
E o administrador, não achei nada no banco que tivesse algo indicando isso, o mais próximo seria o roles, mas ainda assim não achei um exemplo de admin nos modelos de teste.

**Comment by CPeluti** [comment]
> Acho ruim limitar essa consulta ao semestre atual, talvez ter um query param para o semestre seria melhor? Ou realmente não importa as pesquisas dos semestres passados?
> 
> E como saberiamos o semestre atual? Por data não da, um exemplo é esse ano que vão ter 3 semestres

Concordo, seria bom ter um parametro para definir quantos semestres serão considerados nos relatórios. Contudo a principio será utilizado somente consultas do semestre vigente.
Podemos saber qual o semestre atual na hora de extrair a turma do sigaa, lá é possível ver o numero do semestre (2019.2, 2020.1, etc.)



> E o administrador, não achei nada no banco que tivesse algo indicando isso, o mais próximo seria o roles, mas ainda assim não achei um exemplo de admin nos modelos de teste.

No caso seriam as roles mesmo e atualmente falta um exemplo de admin nas seeds do projeto, mas a principio para fazer os relatórios não precisa se preocupar com permissão de quem irá ver. O principal é que eles estejam trazendo todas a informações necessárias para cada uma das visões.
