### ISSUE TITLE
Cadastrar usuários do sistema

### ISSUE THREAD

**Issue by Genaina** [EngSwCIC/CAMAAR#9]
Eu como Administrador
Quero cadastrar professores e alunos do CIC
A fim de que eles acessem o sistema CAMAAR

**Comment by CPeluti** [comment]
Para essa issue é importante pensar como que será feito o cadastro, já que não é possível permitir que os alunos cadastrem sua própria matrícula e nem o coordenador ter que cadastrar todos os alunos manualmente. Uma possível solução é utilizar os email e matriculas obtidos através do sigaa e criar um pré-cadastro com eles.
